alter procedure [dbo].[GetHolderData]
@ACCOUNTNUMBER nvarchar(Max)
as
Begin

        SELECT
        CP.PRODUCTTYPE,
        '' AS PRODUCTTYPENAME,
        BR.BRANCHID,
        BR.BRANCHNAME,
        CP.CUSTOMERID,
        CP.CUSTOMERPRODUCTID,
        CP.BALANCE,
        CP.ACCOUNTNUMBER,
        CP.AMOUNT,
        CP.LASTINSTALLMENTDATE,
        CP.ISFREEZE,
        CP.[STATUS],
        PR.PRODUCTNAME,
        PR.PRODUCTCODE,
        SUM(CP.AMOUNT) as UNCLEARBALANCE
        FROM CUSTOMERPRODUCT CP WITH(NOLOCK)
        LEFT JOIN CUSTOMER CS WITH(NOLOCK) ON CS.CUSTOMERID = CP.CUSTOMERID
        LEFT JOIN BRANCH BR WITH(NOLOCK) ON BR.BRANCHID = CS.BRANCHID
        LEFT JOIN PRODUCT PR WITH(NOLOCK) ON PR.PRODUCTID = CP.PRODUCTID
        LEFT JOIN TRANSACTIONS TR WITH(NOLOCK) ON TR.STATUS = 1 AND CP.CUSTOMERPRODUCTID = TR.CUSTOMERPRODUCTID
        WHERE ACCOUNTNUMBER= @ACCOUNTNUMBER
        GROUP BY
        CP.PRODUCTTYPE,
        BR.BRANCHID,
        BR.BRANCHNAME,
        CP.CUSTOMERID,
        CP.CUSTOMERPRODUCTID,
        CP.BALANCE,
        CP.ACCOUNTNUMBER,
        CP.AMOUNT,
        CP.LASTINSTALLMENTDATE,
        CP.ISFREEZE,
        CP.[STATUS],
        PR.PRODUCTNAME,
        PR.PRODUCTCODE
End

